Update to LVGL9.1 (#64)
* Update PlatformIO demo to LVGL9.1

* Update ci.yml

Trying to fix a 
```
Run actions/setup-python@v1
Error: Version 3.x with arch x64 not found
```
failure on MacOS

* Add a build script that automatically tries to adjust SDL2 include and library paths. Fixes compilation failure on MacOS 14